version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=Javaplayground -Dsonar.organization=Javaplayground -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b7cf028ce5d0a9a1e7eb2986c6992ec632c793df 
